### ISSUE TITLE
Reuse existing role for golang deployment

### ISSUE THREAD

**Issue by lukas-bednar** [cynepco3hahue/kubevirt-ansible#1]
https://github.com/cynepco3hahue/kubevirt-ansible/blob/04d003a35955aead5387b79461f1c65ea80eda86/common/roles/golang/tasks/main.yml#L1

Hi,

there are several maintained roles on ansible galaxy which you can reuse for this purpose and make this repo more lightweight .

For example I think this one is in good shape: https://galaxy.ansible.com/andrewrothstein/go/

**Comment by cynepco3hahue** [comment]
Thanks, will check it, we have the open discussion to merge mine and pkotas repos to single one and move it under the KubeVirt project, so it can be part of the moving process.

**Comment by cynepco3hahue** [comment]
@lukas-bednar I checked and it looks fine, the single question that I have, maybe do you know what kind of verification galaxy roles passed? I mean that everyone can configure some script via Ansible that will send all hosts details to some remote server, so from my point, it not so secure to use external roles.

**Comment by lukas-bednar** [comment]
@cynepco3hahue yes that can happen, but same can happen in other projects ... when you are using packages from pip ... how do you know that it doesn't content some part which will steal some data from you or remove root partition.

anyway I was playing with this role yesterday and it doesn't set GOPATH, which is not nice ...
we can either send PR, or do it in kubevirt role, but I prefer PR or don't do it at all.

**Comment by cynepco3hahue** [comment]
@lukas-bednar I understand your point, at least it some small role so it easy to see some strange code under it :smile: 
I saw it set only GOROOT variable, so I copied `go-path.sh ` to `/etc/profile.d/` under kubevirt role and it worked fine, do you think we must create PR under `https://github.com/andrewrothstein/ansible-go` repositrory?

**Comment by cynepco3hahue** [comment]
@lukas-bednar I found it has some additional repo
`https://github.com/andrewrothstein/ansible-go-dev`, so I believe it exactly what that we need
