### ISSUE TITLE
deploy-openshift.yml playbook doesn't clone openshift-ansible repo as doc says

### ISSUE THREAD

**Issue by lukas-bednar** [cynepco3hahue/kubevirt-ansible#3]
https://github.com/cynepco3hahue/kubevirt-ansible/blob/04d003a35955aead5387b79461f1c65ea80eda86/README.md#L16-L18

The playbook doesn't clone openshift-ansible repository under openshift_ansible_dir.
It fails on 
```
ERROR! the file_name 'kubevirt-ansible/ose-ansible-dir/playbooks/byo/config.yml' does not exist, or is not readable
```

**Comment by lukas-bednar** [comment]
I think we need to remove this line
https://github.com/cynepco3hahue/kubevirt-ansible/blob/0eb5fc11e7c3179aa2759945a78168357a01f730/openshift/roles/prerequisites/tasks/main.yml#L36

and make sure that user clone this repository by himself.

because following include is done before any task is executed ...
https://github.com/cynepco3hahue/kubevirt-ansible/blob/0eb5fc11e7c3179aa2759945a78168357a01f730/deploy-openshift.yml#L12

what do you think ?

**Comment by cynepco3hahue** [comment]
@lukas-bednar yes you right, looks like I do not have other choices.
Any idea how we can to automate it?
